"""first setup

Revision ID: 26a8e8f82e4c
Revises: 
Create Date: 2022-03-22 05:10:39.062461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8e8f82e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_body'), 'task', ['body'], unique=False)
    op.create_index(op.f('ix_task_genre'), 'task', ['genre'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_genre'), table_name='task')
    op.drop_index(op.f('ix_task_body'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
